services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: quang232003
    ports:
      - "1200:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: